-- SHARED MARKDOWN RULES (rumdl)
--------------------------------------------------
-- The rules live in a file generated by module.nix. A file is
-- required: the LSP server ignores overrides passed on the
-- command line, while `configPath` works and applies outside
-- projects carrying their own .rumdl.toml.

local M = {}

-- Time allowed to one rumdl run. A first save of a 635 KB file
-- took ~2.8 s of rumdl alone and went past 3 s once the LSP and
-- linters shared the CPU: conform dropped rumdl and the file was
-- saved half formatted. The editor waits this long at most.
M.TIMEOUT_MS = 10000

-- Path to the rules file, nil outside the Nix wrapper --
function M.config_path()
	local path = nixInfo(nil, "settings", "markdown", "rules_file")
	if path and vim.fn.filereadable(path) == 1 then
		return path
	end
	return nil
end

-- Arguments for the command-line subcommands --
function M.args()
	local path = M.config_path()
	if path then
		return { "--config", path }
	end

	-- Outside the wrapper, fall back to inline overrides
	local len = nixInfo(75, "settings", "markdown", "line_length")
	return {
		"--config",
		'global.flavor = "pandoc"',
		"--config",
		"MD013.line-length = " .. tostring(len),
		"--config",
		"MD013.strict = false",
		"--config",
		"MD013.headings = false",
		"--config",
		"MD013.code-blocks = false",
		"--config",
		"MD013.tables = false",
		"--config",
		'global.disable = ["MD018", "MD024", "MD025", "MD041", "MD045"]',
	}
end

-- SAVE PIPELINE
--------------------------------------------------
-- rumdl, mdwrap, rumdl: what `:w` and `:MdFormatDir` run on a
-- markdown buffer. The first pass fixes list indentation and
-- markers before mdwrap measures the lines. With mdwrap first,
-- rumdl then moved text sideways (a nested item from 4 spaces
-- to 2) and the next save rewrapped it again. The extra pass
-- measured +6..40 ms at 64 KB, +0.3..0.6 s at 635 KB.
function M.format(bufnr)
	local conform = require("conform")
	local mdwrap = require("core.mdwrap")
	local opts = { bufnr = bufnr, timeout_ms = M.TIMEOUT_MS, formatters = { "rumdl" } }
	-- rumdl deletes 3+ trailing spaces with their hard break
	mdwrap.normalize_breaks(bufnr)
	conform.format(opts)
	mdwrap.wrap(bufnr)
	conform.format(opts)
end

return M
